language: cpp
cache: apt
branches:
  except:
  - mdd
  - soct
env:
  matrix:
     - UBUNTU_DIST=xenial
       BUILD_TYPE=MinSizeRel
     #- UBUNTU_DIST=bionic
     #  BUILD_TYPE=MinSizeRel
              
services:
  - docker

install: true

script:
  ### build and run tests with docker
  - docker build --build-arg UBUNTU=${UBUNTU_DIST} --build-arg BUILD_TYPE=${BUILD_TYPE} -t seahorn/clam_5.0:${UBUNTU_DIST} -f docker/clam-full-size-rel.Dockerfile .
  
  - 'if [ "$TRAVIS_EVENT_TYPE" = "cron" ] ;
        then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          && docker push seahorn/clam_5.0:${UBUNTU_DIST};
     fi '

